
export const glossario: { termine: string; categoria: string; definizione: string }[] = [
  { termine: 'Abrogare', categoria: 'Fonti del diritto', definizione: 'Eliminare una norma giuridica dall\'ordinamento per effetto di una norma successiva, di un referendum popolare o della dichiarazione di incostituzionalità.' },
  { termine: 'Abnorme', categoria: 'Diritto processuale', definizione: 'Indica un atto o un provvedimento che, per la sua particolarità, si presume fuori da qualsiasi regola giuridica.' },
  { termine: 'Affinità', categoria: 'Diritto di famiglia', definizione: 'Condizione che lega uno dei due coniugi ai parenti dell\'altro.' },
  { termine: 'Aggravanti comuni', categoria: 'Diritto penale', definizione: 'Insieme di circostanze che aggravano il reato quando non reggono elementi costitutivi o circostanze aggravanti speciali, aumentandone la pena.' },
  { termine: 'Aliquota', categoria: 'Diritto tributario', definizione: 'Percentuale che deve essere applicata alla base imponibile ai fini del calcolo di un\'imposta.' },
  { termine: 'Ammenda', categoria: 'Diritto penale', definizione: 'Sanzione pecuniaria che consiste nel pagamento allo Stato di una somma da 2 a 1032 euro.' },
  { termine: 'Amnistia', categoria: 'Diritto penale', definizione: 'Provvedimento legislativo che estingue il reato e le relative pene, riferito a fatti commessi prima della sua entrata in vigore. È concessa con legge approvata a maggioranza dei due terzi del Parlamento.' },
  { termine: 'Annullabile', categoria: 'Diritto civile', definizione: 'Atto che presenta elementi i quali, se rilevati, possono renderlo nullo.' },
  { termine: 'Apertura di credito bancario', categoria: 'Diritto bancario', definizione: 'Contratto con il quale la banca si vincola a tenere a disposizione dell\'altra parte una somma di denaro per un periodo stabilito nel contratto.' },
  { termine: 'Appalto', categoria: 'Diritto civile', definizione: 'Contratto con il quale una parte assume il compimento di un\'opera o di un servizio verso un corrispettivo in denaro, con organizzazione dei mezzi necessari e con gestione a proprio rischio.' },
  { termine: 'Archiviazione', categoria: 'Diritto processuale', definizione: 'Provvedimento con cui il giudice per le indagini preliminari, su richiesta del pubblico ministero, chiude il procedimento penale al termine delle indagini.' },
  { termine: 'Arresti domiciliari', categoria: 'Diritto penale', definizione: 'Misura cautelare coercitiva consistente nell\'obbligo di rimanere nella propria abitazione o in altro luogo di privata dimora.' },
  { termine: 'Arresto', categoria: 'Diritto penale', definizione: 'Pena detentiva da un minimo di cinque giorni a un massimo di tre anni di carcere, prevista per le contravvenzioni.' },
  { termine: 'Arringa', categoria: 'Diritto processuale', definizione: 'Discussione conclusiva degli avvocati penalisti svolta prima della sentenza nel dibattimento.' },
  { termine: 'Associazione per delinquere', categoria: 'Diritto penale', definizione: 'Unione di almeno tre persone finalizzata alla commissione di reati, non necessariamente di stampo mafioso.' },
  { termine: 'Assoluzione', categoria: 'Diritto processuale', definizione: 'Provvedimento del giudice con cui viene riconosciuta l\'innocenza dell\'imputato.' },
  { termine: 'Attenuanti comuni', categoria: 'Diritto penale', definizione: 'Circostanze che attenuano il reato, quando non vi sono elementi costitutivi o circostanze attenuanti speciali, diminuendone la pena.' },
  { termine: 'Attenuanti generiche', categoria: 'Diritto penale', definizione: 'Beneficio concesso dal giudice all\'imputato nella sentenza di condanna, consistente in un insieme di circostanze supplementari volte a diminuire ulteriormente la pena.' },
  { termine: 'Attore', categoria: 'Diritto processuale', definizione: 'Soggetto che promuove un processo civile, instaurando il giudizio nei confronti del convenuto.' },
  { termine: 'Bancarotta fraudolenta', categoria: 'Diritto penale', definizione: 'Reato commesso dall\'imprenditore dichiarato fallito che ha occultato, distrutto o dissipato i propri beni, esposto debiti inesistenti o falsificato le scritture contabili allo scopo di danneggiare i creditori.' },
  { termine: 'Bancarotta semplice', categoria: 'Diritto penale', definizione: 'Reato commesso dall\'imprenditore dichiarato fallito che ha tenuto comportamenti imprudenti o dispendiosi tali da aggravare il proprio dissesto economico.' },
  { termine: 'Base imponibile', categoria: 'Diritto tributario', definizione: 'Valore su cui viene applicata l\'aliquota per il calcolo di un\'imposta.' },
  { termine: 'Bigamia', categoria: 'Diritto penale', definizione: 'Reato commesso da chi, essendo già legato da matrimonio avente effetti civili, ne contrae un altro.' },
  { termine: 'Calunnia', categoria: 'Diritto penale', definizione: 'Reato commesso da chi incolpa di un reato una persona che sa innocente, tramite denuncia, querela, richiesta o istanza, anche se anonima o sotto falso nome.' },
  { termine: 'Cancelleria', categoria: 'Diritto processuale', definizione: 'Segreteria del giudice, ufficio che cura la gestione amministrativa degli atti processuali.' },
  { termine: 'Capo di imputazione', categoria: 'Diritto processuale', definizione: 'Descrizione dettagliata scritta di un fatto contestato all\'imputato, con l\'indicazione degli articoli di legge violati.' },
  { termine: 'Carico pendente', categoria: 'Diritto processuale', definizione: 'Processo penale in corso a carico di una persona.' },
  { termine: 'Chiamata in correità', categoria: 'Diritto processuale', definizione: 'Confessione di aver commesso un reato fatta all\'autorità giudiziaria, con contestuale accusa di altre persone di aver partecipato alla commissione del reato stesso.' },
  { termine: 'Citazione', categoria: 'Diritto processuale', definizione: 'Atto con cui una parte viene convocata in giudizio; può assumere carattere di invito scritto o di vero e proprio ordine.' },
  { termine: 'Comodato', categoria: 'Diritto civile', definizione: 'Contratto con il quale una parte consegna ad un\'altra una cosa mobile o immobile, per un tempo o per un uso determinato, con l\'obbligo di restituirla. È essenzialmente gratuito.' },
  { termine: 'Comma', categoria: 'Fonti del diritto', definizione: 'Periodo di un articolo di legge o di un codice che inizia dopo un punto e a capo.' },
  { termine: 'Concorso di persone', categoria: 'Diritto penale', definizione: 'Collaborazione di più soggetti alla commissione di un medesimo reato, ciascuno dei quali risponde penalmente dell\'illecito commesso.' },
  { termine: 'Concussione', categoria: 'Diritto penale', definizione: 'Reato commesso da un pubblico ufficiale o da un incaricato di pubblico servizio che, abusando della sua posizione, costringe o induce taluno a dare o promettere denaro o altri vantaggi.' },
  { termine: 'Condanna', categoria: 'Diritto processuale', definizione: 'Provvedimento del giudice con cui viene accertata la colpevolezza dell\'imputato e viene applicata la pena prevista dalla legge.' },
  { termine: 'Contravvenzioni', categoria: 'Diritto penale', definizione: 'Categoria di reati per i quali è prevista la pena dell\'arresto e/o dell\'ammenda, di minore gravità rispetto ai delitti.' },
  { termine: 'Contumace', categoria: 'Diritto processuale', definizione: 'Soggetto che, pur essendo libero e non irreperibile, decide di non partecipare al processo che lo vede imputato o convenuto.' },
  { termine: 'Convenuto', categoria: 'Diritto processuale', definizione: 'Soggetto che subisce un processo civile, chiamato in giudizio dall\'attore.' },
  { termine: 'Corpo del reato', categoria: 'Diritto penale', definizione: 'Tutte le cose sulle quali o per mezzo delle quali è stato commesso il reato, nonché le cose che ne costituiscono il risultato, il profitto o il prezzo.' },
  { termine: 'Custodia cautelare', categoria: 'Diritto penale', definizione: 'Carcerazione preventiva che precede la sentenza definitiva, disposta per salvaguardare le prove, evitare la fuga o prevenire la reiterazione del reato.' },
  { termine: 'Delitti', categoria: 'Diritto penale', definizione: 'Categoria di reati per i quali è prevista la pena dell\'ergastolo, della reclusione e/o della multa, di maggiore gravità rispetto alle contravvenzioni.' },
  { termine: 'Denuncia', categoria: 'Diritto processuale', definizione: 'Descrizione dettagliata dei fatti che inducono a reato, presentata da una persona all\'autorità giudiziaria, che non prevede una esplicita richiesta di condanna.' },
  { termine: 'Deontologia', categoria: 'Diritto professionale', definizione: 'Insieme di regole scritte che disciplinano il comportamento di ogni professionista nei confronti dei clienti e dei colleghi.' },
  { termine: 'Depenalizzare', categoria: 'Diritto penale', definizione: 'Eliminare a un illecito il carattere penale, lasciandolo spesso nel campo di altri tipi di illeciti (civili o amministrativi).' },
  { termine: 'Derubricare', categoria: 'Diritto penale', definizione: 'Qualificare diversamente un reato, sostituendolo con uno di gravità inferiore.' },
  { termine: 'Detenzione domiciliare', categoria: 'Diritto penale', definizione: 'Misura alternativa alla detenzione carceraria che consente al condannato di scontare la pena nella propria abitazione.' },
  { termine: 'Dibattimento', categoria: 'Diritto processuale', definizione: 'Parte centrale del processo penale, nella quale si raccolgono tutte le prove e le testimonianze in contraddittorio tra le parti.' },
  { termine: 'Diffamazione', categoria: 'Diritto penale', definizione: 'Reato commesso da chi offende l\'altrui reputazione comunicando con più persone o per mezzo della stampa.' },
  { termine: 'Dispositivo', categoria: 'Diritto processuale', definizione: 'Parte della sentenza contenente le generalità dell\'imputato e la decisione del giudice, distinta dalla motivazione.' },
  { termine: 'Dolo', categoria: 'Diritto penale', definizione: 'Elemento soggettivo del reato consistente nella coscienza e volontà di commettere il fatto previsto dalla legge come reato.' },
  { termine: 'Donazione', categoria: 'Diritto civile', definizione: 'Contratto con il quale, per spirito di liberalità, una parte arricchisce l\'altra, trasferendole un diritto o assumendo verso di essa un\'obbligazione.' },
  { termine: 'Eccepire', categoria: 'Diritto processuale', definizione: 'Far presente oralmente al giudice una scorrettezza processuale o un\'eccezione di diritto.' },
  { termine: 'Efficacia erga omnes', categoria: 'Diritto costituzionale', definizione: 'Efficacia di un atto giuridico che vale nei confronti di tutti i soggetti dell\'ordinamento, e non solo tra le parti.' },
  { termine: 'Emendamento', categoria: 'Fonti del diritto', definizione: 'Modifica apportata a un testo normativo nel corso del procedimento legislativo.' },
  { termine: 'Esercizio dell\'azione penale', categoria: 'Diritto processuale', definizione: 'Richiesta di processo per una determinata persona da parte del Pubblico Ministero quando vi sono sufficienti indizi di reato e non vi sono condizioni per l\'archiviazione.' },
  { termine: 'Fattispecie', categoria: 'Teoria del diritto', definizione: 'Parte della norma giuridica nella quale sono descritte le condizioni astratte al verificarsi delle quali la norma stessa è applicabile.' },
  { termine: 'Fatto giuridico', categoria: 'Teoria del diritto', definizione: 'Evento previsto dalla fattispecie di una norma, al cui verificarsi l\'ordinamento ricollega effetti giuridici.' },
  { termine: 'Favor rei', categoria: 'Diritto penale', definizione: 'Principio secondo cui si applica all\'imputato la legge più favorevole quando essa cambia nel corso del processo.' },
  { termine: 'Fermo', categoria: 'Diritto penale', definizione: 'Misura restrittiva adottata dal PM o dalla polizia giudiziaria quando sussiste fondato pericolo di fuga dell\'indiziato di un grave delitto.' },
  { termine: 'Fideiussione', categoria: 'Diritto civile', definizione: 'Contratto di garanzia con cui un soggetto si impegna verso il creditore a garantire l\'adempimento di un\'obbligazione altrui.' },
  { termine: 'Flagranza', categoria: 'Diritto penale', definizione: 'Condizione di chi viene colto nell\'atto di commettere un reato ovvero chi, subito dopo il reato, è inseguito dalle forze dell\'ordine o da altre persone.' },
  { termine: 'Furto', categoria: 'Diritto penale', definizione: 'Reato consistente nella sottrazione di una cosa mobile altrui, al fine di trarne profitto per sé o per altri.' },
  { termine: 'Giudizio abbreviato', categoria: 'Diritto processuale', definizione: 'Rito speciale del processo penale privo di dibattimento, richiesto dall\'imputato, che prevede in caso di condanna la riduzione di un terzo della pena.' },
  { termine: 'Giudizio direttissimo', categoria: 'Diritto processuale', definizione: 'Processo speciale previsto per una persona arrestata in flagranza di reato, che deve iniziare entro quarantotto ore dall\'arresto.' },
  { termine: 'Giudizio immediato', categoria: 'Diritto processuale', definizione: 'Tipo di processo penale che non prevede l\'udienza preliminare, richiesto esclusivamente quando la prova è evidente.' },
  { termine: 'Giurisprudenza', categoria: 'Teoria del diritto', definizione: 'Insieme delle sentenze dei giudici, in particolare della Corte di Cassazione e della Corte Costituzionale, che costituiscono un precedente interpretativo.' },
  { termine: 'Gratuito patrocinio', categoria: 'Diritto processuale', definizione: 'Istituto che consente ai cittadini con reddito insufficiente di essere assistiti gratuitamente da un avvocato a spese dello Stato.' },
  { termine: 'Grazia', categoria: 'Diritto costituzionale', definizione: 'Provvedimento del Presidente della Repubblica che condona, in tutto o in parte, la pena inflitta a un condannato, senza estinguere il reato né le pene accessorie.' },
  { termine: 'Illecito', categoria: 'Teoria del diritto', definizione: 'Comportamento o atto che viola una disposizione di legge, cui l\'ordinamento ricollega una sanzione.' },
  { termine: 'Imposta', categoria: 'Diritto tributario', definizione: 'Prelievo obbligatorio che lo Stato, le regioni e gli enti locali effettuano sul patrimonio dei cittadini per finanziare le spese pubbliche.' },
  { termine: 'Impugnazione', categoria: 'Diritto processuale', definizione: 'Rimedio processuale consistente in un\'obiezione scritta e motivata avverso la decisione di un giudice o di un\'altra autorità.' },
  { termine: 'Imputato', categoria: 'Diritto processuale', definizione: 'Persona sottoposta a un processo penale, nei cui confronti è stata esercitata l\'azione penale.' },
  { termine: 'Incensurato', categoria: 'Diritto penale', definizione: 'Persona che non ha mai subito una condanna penale definitiva.' },
  { termine: 'Indagato', categoria: 'Diritto processuale', definizione: 'Persona accusata di un reato nel corso delle indagini preliminari, prima che venga esercitata l\'azione penale.' },
  { termine: 'Indizio', categoria: 'Diritto processuale', definizione: 'Elemento di prova che, da solo, non è sufficiente a dimostrare la colpevolezza ma che, unitamente ad altri, può contribuire a formare il convincimento del giudice.' },
  { termine: 'Indulto', categoria: 'Diritto penale', definizione: 'Provvedimento del Presidente della Repubblica che condona, in tutto o in parte, la pena inflitta, senza estinguere il reato né le pene accessorie, a differenza dell\'amnistia.' },
  { termine: 'Ingiuria', categoria: 'Diritto penale', definizione: 'Reato (oggi depenalizzato e trasformato in illecito civile) commesso da chi offende l\'onore o il decoro di una persona presente.' },
  { termine: 'Interrogatorio', categoria: 'Diritto processuale', definizione: 'Serie di domande sottoposte all\'indagato dal Pubblico Ministero o dalla Polizia Giudiziaria, alle quali il soggetto può scegliere di non rispondere.' },
  { termine: 'Ispezione', categoria: 'Diritto processuale', definizione: 'Operazione investigativa disposta con decreto motivato, effettuata su persone, luoghi o cose per accertare tracce e materiali del reato.' },
  { termine: 'Istituto giuridico', categoria: 'Teoria del diritto', definizione: 'Insieme organico di norme che regolano un determinato fatto o rapporto giuridico.' },
  { termine: 'Liberazione anticipata', categoria: 'Diritto penale', definizione: 'Riduzione di pena di quarantacinque giorni per ogni singolo semestre scontato dal condannato che abbia dimostrato partecipazione all\'opera di rieducazione.' },
  { termine: 'Locazione', categoria: 'Diritto civile', definizione: 'Contratto con il quale una parte si impegna a far godere ad un\'altra una cosa mobile o immobile per un dato tempo, verso corrispettivo.' },
  { termine: 'Mandato', categoria: 'Diritto processuale', definizione: 'Documento scritto con il quale una persona indica l\'avvocato dal quale desidera essere assistita nel processo civile.' },
  { termine: 'Minore imputabile', categoria: 'Diritto penale', definizione: 'Chi ha già compiuto i quattordici anni ma non ancora i diciotto, soggetto a un regime penale differenziato presso il tribunale per i minorenni.' },
  { termine: 'Motivazione', categoria: 'Diritto processuale', definizione: 'Parte della sentenza contenente l\'esposizione dei fatti, dello svolgimento del processo, degli elementi giuridici e le ragioni della decisione del giudice.' },
  { termine: 'Multa', categoria: 'Diritto penale', definizione: 'Sanzione pecuniaria prevista per i delitti, consistente nel pagamento allo Stato di una somma da 5,16 a 5.164,57 euro.' },
  { termine: 'Mutuo', categoria: 'Diritto civile', definizione: 'Contratto con il quale una parte consegna all\'altra una determinata quantità di denaro o altre cose fungibili, con obbligo di restituzione della stessa specie e qualità.' },
  { termine: 'Ne bis in idem', categoria: 'Diritto processuale', definizione: 'Principio in base al quale nessuno può essere processato due volte per lo stesso fatto di reato già definitivamente giudicato.' },
  { termine: 'Nomina', categoria: 'Diritto processuale', definizione: 'Atto scritto con il quale l\'indagato o l\'imputato indica l\'avvocato da cui desidera essere assistito nel procedimento penale.' },
  { termine: 'Notificazione', categoria: 'Diritto processuale', definizione: 'Atto con cui si porta ufficialmente a conoscenza del destinatario un atto processuale, mediante consegna di copia da parte dell\'ufficiale giudiziario o di altri soggetti abilitati.' },
  { termine: 'Nullità', categoria: 'Diritto civile', definizione: 'Forma più grave di invalidità dell\'atto giuridico, che lo priva di ogni effetto sin dall\'origine, rilevabile d\'ufficio e da chiunque vi abbia interesse.' },
  { termine: 'Oblazione', categoria: 'Diritto penale', definizione: 'Istituto che consente l\'estinzione del reato contravvenzionale mediante il pagamento di una somma di denaro prima del decreto di condanna.' },
  { termine: 'Omissione di soccorso', categoria: 'Diritto penale', definizione: 'Reato commesso da chi trova una persona in pericolo o bisognosa di assistenza e omette di prestarle soccorso o di darne avviso all\'autorità.' },
  { termine: 'Ordinamento giuridico', categoria: 'Teoria del diritto', definizione: 'Sistema organico di norme che regolano la vita di una comunità statale, caratterizzato da completezza, coerenza e unitarietà.' },
  { termine: 'Ordinanza', categoria: 'Diritto processuale', definizione: 'Provvedimento motivato del giudice, adottato nel corso del processo, che può essere revocato o modificato dallo stesso giudice che l\'ha emesso.' },
  { termine: 'Parte civile', categoria: 'Diritto processuale', definizione: 'Il soggetto che ha subito il reato e decide di costituirsi nel processo penale per ottenere dall\'imputato il risarcimento del danno.' },
  { termine: 'Patteggiamento', categoria: 'Diritto processuale', definizione: 'Rito speciale con cui l\'imputato e il pubblico ministero concordano l\'applicazione di una pena ridotta fino a un terzo, senza svolgimento del dibattimento.' },
  { termine: 'Patto di famiglia', categoria: 'Diritto civile', definizione: 'Contratto con cui l\'imprenditore trasferisce, in tutto o in parte, l\'azienda o le proprie partecipazioni societarie a uno o più discendenti.' },
  { termine: 'Peculato', categoria: 'Diritto penale', definizione: 'Reato commesso dal pubblico ufficiale che si appropria di denaro o altra cosa mobile di cui ha il possesso per ragione del suo ufficio.' },
  { termine: 'Perdono giudiziale', categoria: 'Diritto penale', definizione: 'Istituto del diritto penale minorile che consente al giudice, sussistendone le condizioni, di astenersi dal rinvio a giudizio o dalla condanna del minore.' },
  { termine: 'Perizia', categoria: 'Diritto processuale', definizione: 'Mezzo di prova consistente nell\'accertamento di fatti o valutazioni che richiedono specifiche competenze tecniche, scientifiche o artistiche, affidato a un esperto nominato dal giudice.' },
  { termine: 'Perquisizione', categoria: 'Diritto processuale', definizione: 'Operazione investigativa disposta con decreto motivato per ricercare il corpo del reato o cose pertinenti al reato sulla persona o in un determinato luogo.' },
  { termine: 'Persona offesa', categoria: 'Diritto processuale', definizione: 'Soggetto che ha subito direttamente il danno derivante dal reato, titolare di specifici diritti nel corso del procedimento penale.' },
  { termine: 'Persone giuridiche', categoria: 'Diritto civile', definizione: 'Enti — associazioni riconosciute, fondazioni, società di capitali ed enti pubblici — cui l\'ordinamento riconosce soggettività giuridica distinta da quella delle persone fisiche che li compongono.' },
  { termine: 'Polizia giudiziaria', categoria: 'Diritto processuale', definizione: 'Insieme degli organi e degli agenti che, sotto la direzione e la vigilanza del pubblico ministero, svolgono attività investigativa e di accertamento dei reati.' },
  { termine: 'Prescrizione', categoria: 'Diritto civile', definizione: 'Estinzione di un diritto soggettivo o dell\'azione penale per il decorso del tempo stabilito dalla legge senza che il diritto sia stato esercitato.' },
  { termine: 'Preterintenzione', categoria: 'Diritto penale', definizione: 'Forma di responsabilità penale in cui dall\'azione voluta dall\'agente deriva un evento più grave di quello voluto, come nell\'omicidio preterintenzionale.' },
  { termine: 'Procuratore Generale', categoria: 'Diritto processuale', definizione: 'Magistrato che svolge le funzioni di Pubblico Ministero in Corte di Appello, in Corte di Cassazione o al tribunale di sorveglianza.' },
  { termine: 'Promulgazione', categoria: 'Fonti del diritto', definizione: 'Atto con cui il Presidente della Repubblica attesta l\'esistenza della legge e ne ordina l\'esecuzione, condizione necessaria per la sua entrata in vigore.' },
  { termine: 'Proscioglimento', categoria: 'Diritto processuale', definizione: 'Provvedimento liberatorio pronunciato all\'udienza preliminare quando il giudice ritiene che non vi siano elementi sufficienti per rinviare l\'imputato a giudizio.' },
  { termine: 'Pubblico Ministero', categoria: 'Diritto processuale', definizione: 'Organo della magistratura requirente che esercita l\'azione penale, dirige le indagini preliminari e sostiene l\'accusa nel processo penale.' },
  { termine: 'Querela', categoria: 'Diritto processuale', definizione: 'Atto con cui la persona offesa dal reato manifesta la volontà che si proceda penalmente nei confronti dell\'autore del fatto, richiedendo esplicitamente la condanna.' },
  { termine: 'Rapporto giuridico', categoria: 'Teoria del diritto', definizione: 'Relazione tra soggetti dell\'ordinamento giuridico, disciplinata da norme di diritto, da cui derivano diritti e obblighi reciproci.' },
  { termine: 'Reato', categoria: 'Diritto penale', definizione: 'Fatto illecito previsto dalla legge penale come tale e punito con una sanzione penale. Si distingue in delitti e contravvenzioni.' },
  { termine: 'Reato comune', categoria: 'Diritto penale', definizione: 'Reato che può essere commesso da chiunque, a differenza del reato proprio che richiede una qualifica soggettiva speciale.' },
  { termine: 'Reato proprio', categoria: 'Diritto penale', definizione: 'Reato che può essere commesso solo da soggetti che rivestono una determinata qualifica, come il pubblico ufficiale o il militare.' },
  { termine: 'Recidiva', categoria: 'Diritto penale', definizione: 'Circostanza aggravante che ricorre quando il soggetto, dopo essere stato condannato per un delitto non colposo, ne commette un altro.' },
  { termine: 'Reclusione', categoria: 'Diritto penale', definizione: 'Pena detentiva principale prevista per i delitti, che può andare da un minimo di quindici giorni a un massimo di ventiquattro anni.' },
  { termine: 'Requisitoria', categoria: 'Diritto processuale', definizione: 'Discussione conclusiva del Pubblico Ministero al termine del processo penale, contenente l\'illustrazione delle prove raccolte e le richieste di assoluzione o condanna.' },
  { termine: 'Responsabile civile', categoria: 'Diritto processuale', definizione: 'Soggetto estraneo al reato che è chiamato a rispondere civilmente, in solido con l\'imputato, del danno cagionato dal reato.' },
  { termine: 'Rogatoria', categoria: 'Diritto processuale', definizione: 'Richiesta di un\'autorità giudiziaria rivolta ad altra autorità nazionale o straniera per compiere atti processuali fuori dalla propria circoscrizione o all\'estero.' },
  { termine: 'Semilibertà', categoria: 'Diritto penale', definizione: 'Misura alternativa alla detenzione che consente al condannato di trascorrere parte della giornata fuori dal carcere per svolgere attività lavorative o di studio.' },
  { termine: 'Sentenza', categoria: 'Diritto processuale', definizione: 'Provvedimento giurisdizionale finale con cui il giudice definisce il processo, decidendo nel merito della controversia o dell\'imputazione.' },
  { termine: 'Sospensione condizionale della pena', categoria: 'Diritto penale', definizione: 'Beneficio con cui il giudice sospende l\'esecuzione della pena per un determinato periodo, subordinandone la definitiva remissione alla condizione che il condannato non commetta ulteriori reati.' },
  { termine: 'Tassa', categoria: 'Diritto tributario', definizione: 'Corrispettivo che un cittadino deve pagare a un ente pubblico in cambio di uno specifico servizio o prestazione erogata in suo favore.' },
  { termine: 'Testamento', categoria: 'Diritto civile', definizione: 'Atto revocabile con cui una persona dispone, per il tempo successivo alla propria morte, di tutti i propri beni o di parte di essi.' },
  { termine: 'Testimonianza de relato', categoria: 'Diritto processuale', definizione: 'Testimonianza resa sulla base di ciò che il testimone ha appreso da altri, avente un valore probatorio limitato.' },
  { termine: 'Testo unico', categoria: 'Fonti del diritto', definizione: 'Norma che raccoglie e disciplina organicamente una determinata materia, coordinando disposizioni legislative preesistenti.' },
  { termine: 'Transazione', categoria: 'Diritto civile', definizione: 'Contratto con il quale le parti, facendosi reciproche concessioni, pongono fine a una lite già iniziata o prevengono una lite che può sorgere tra loro.' },
  { termine: 'Tributo', categoria: 'Diritto tributario', definizione: 'Qualsiasi prelievo coattivo di ricchezza effettuato dallo Stato o da altri enti pubblici per far fronte alle spese pubbliche, comprensivo di imposte, tasse e contributi.' },
  { termine: 'Udienza', categoria: 'Diritto processuale', definizione: 'Seduta del giudice in cui si svolgono gli atti del processo alla presenza delle parti e, ove previsto, del pubblico.' },
  { termine: 'Udienza preliminare', categoria: 'Diritto processuale', definizione: 'Prima udienza del processo penale, svolta a porte chiuse, in cui il giudice decide se rinviare l\'imputato a giudizio o pronunciare sentenza di non luogo a procedere.' },
  { termine: 'Uguaglianza', categoria: 'Diritto costituzionale', definizione: 'Principio fondamentale della Costituzione italiana (art. 3) che sancisce la pari dignità sociale e l\'eguaglianza di tutti i cittadini davanti alla legge.' },
  { termine: 'Usucapione', categoria: 'Diritto civile', definizione: 'Modo di acquisto della proprietà a titolo originario che si realizza attraverso il possesso continuato, pacifico e pubblico di un bene per il tempo stabilito dalla legge (venti anni per gli immobili).' },
  { termine: 'Usura', categoria: 'Diritto penale', definizione: 'Reato commesso da chi si fa dare o promettere interessi o altri vantaggi usurari in corrispettivo di una prestazione di denaro o di altra utilità, approfittando dello stato di difficoltà economica altrui.' },
  { termine: 'Vacatio legis', categoria: 'Fonti del diritto', definizione: 'Periodo di tempo intercorrente tra la pubblicazione di una legge nella Gazzetta Ufficiale e la sua effettiva entrata in vigore, ordinariamente di quindici giorni.' },
  { termine: 'Vendita', categoria: 'Diritto civile', definizione: 'Contratto con cui una parte trasferisce alla controparte la proprietà di una cosa o un altro diritto verso il pagamento di un prezzo.' },
  { termine: 'Verbale', categoria: 'Diritto processuale', definizione: 'Atto scritto che documenta lo svolgimento di un\'attività giudiziaria o amministrativa, redatto dal cancelliere o da altro pubblico ufficiale.' },
  { termine: 'Vizio', categoria: 'Teoria del diritto', definizione: 'Anomalia, difetto o irregolarità che colpisce un atto giuridico, potendone determinare l\'invalidità nelle forme della nullità o dell\'annullabilità.' },
  { termine: 'Abrogazione', categoria: 'Fonti del diritto', definizione: 'Cessazione di efficacia di una norma giuridica per effetto di una norma successiva incompatibile, di una legge che la elimina espressamente, o di un referendum popolare abrogativo.' },
  { termine: 'Decreto legge', categoria: 'Fonti del diritto', definizione: 'Atto normativo con forza di legge emanato dal Governo in casi straordinari di necessità e urgenza, che deve essere convertito in legge dal Parlamento entro sessanta giorni.' },
  { termine: 'Decreto legislativo', categoria: 'Fonti del diritto', definizione: 'Atto normativo emanato dal Governo su delega del Parlamento, nei limiti dei principi e criteri direttivi stabiliti dalla legge delega.' },
  { termine: 'Espropriazione', categoria: 'Diritto amministrativo', definizione: 'Provvedimento con cui la pubblica amministrazione, per motivi di pubblica utilità e previo indennizzo, trasferisce coattivamente la proprietà di un bene dal privato allo Stato o a un altro ente pubblico.' },
  { termine: 'Habeas corpus', categoria: 'Diritto costituzionale', definizione: 'Principio di garanzia della libertà personale che impone che ogni detenzione sia autorizzata dall\'autorità giudiziaria e che il detenuto possa contestarne la legittimità.' },
  { termine: 'Incostituzionalità', categoria: 'Diritto costituzionale', definizione: 'Vizio che colpisce una norma in contrasto con la Costituzione, accertato dalla Corte costituzionale con sentenza avente efficacia erga omnes.' },
  { termine: 'Legge delega', categoria: 'Fonti del diritto', definizione: 'Legge con cui il Parlamento attribuisce al Governo il potere di emanare decreti legislativi, indicando oggetto, principi direttivi e termine per l\'esercizio della delega.' },
  { termine: 'Ricorso in Cassazione', categoria: 'Diritto processuale', definizione: 'Impugnazione straordinaria davanti alla Corte Suprema di Cassazione, ammessa per violazione di legge, volta ad assicurare l\'uniforme interpretazione del diritto.' },
  { termine: 'Sussidiarietà', categoria: 'Diritto amministrativo', definizione: 'Principio per cui le funzioni amministrative sono attribuite all\'ente più vicino al cittadino, salvo che la loro natura richieda l\'intervento di un livello istituzionale superiore.' },
  { termine: 'Contraddittorio', categoria: 'Diritto processuale', definizione: 'Principio fondamentale del processo che garantisce a ciascuna parte il diritto di essere ascoltata e di replicare alle argomentazioni della controparte, davanti a un giudice terzo e imparziale.' },
  { termine: 'Dottrina', categoria: 'Teoria del diritto', definizione: 'Insieme degli studiosi del diritto e delle loro elaborazioni scientifiche, che costituisce una delle fonti di cognizione del diritto, pur non avendo forza normativa vincolante.' },
  { termine: 'Giurisdizione', categoria: 'Diritto processuale', definizione: 'Potere dello Stato di risolvere le controversie giuridiche attraverso l\'applicazione del diritto da parte di organi imparziali e indipendenti.' },
  { termine: 'Legittimità costituzionale', categoria: 'Diritto costituzionale', definizione: 'Conformità di una norma di legge ai principi e alle disposizioni della Costituzione, verificata dalla Corte costituzionale su questione sollevata dai giudici.' },
  { termine: 'Norma giuridica', categoria: 'Teoria del diritto', definizione: 'Regola di condotta generale e astratta, posta dall\'ordinamento giuridico e assistita dalla possibilità di coercizione, che disciplina i rapporti tra i soggetti di diritto.' },
  { termine: 'Nullum crimen sine lege', categoria: 'Diritto penale', definizione: 'Principio fondamentale del diritto penale in base al quale nessuno può essere punito per un fatto che non era previsto dalla legge come reato al momento della sua commissione.' },
  { termine: 'Obbligazione', categoria: 'Diritto civile', definizione: 'Rapporto giuridico in virtù del quale un soggetto (debitore) è tenuto a eseguire una prestazione patrimonialmente valutabile nei confronti di un altro soggetto (creditore).' },
  { termine: 'Responsabilità civile', categoria: 'Diritto civile', definizione: 'Obbligo di risarcire il danno ingiusto cagionato ad altri, che sorge dal fatto illecito (responsabilità extracontrattuale) o dall\'inadempimento di un\'obbligazione (responsabilità contrattuale).' },
  { termine: 'Sequestro', categoria: 'Diritto processuale', definizione: 'Misura cautelare reale o probatoria con cui viene sottratta la disponibilità di un bene al suo titolare, per esigenze processuali o preventive.' },
  { termine: 'Soggetto di diritto', categoria: 'Teoria del diritto', definizione: 'Entità — persona fisica o giuridica — cui l\'ordinamento riconosce la capacità di essere titolare di diritti e di obblighi giuridici.' },
  { termine: 'Solidarietà', categoria: 'Diritto civile', definizione: 'Vincolo che lega più debitori o più creditori in un\'obbligazione, per cui ciascun debitore è tenuto all\'adempimento dell\'intera prestazione e ciascun creditore può pretenderla per intero.' },
  { termine: 'Successione', categoria: 'Diritto civile', definizione: 'Fenomeno giuridico per cui una persona subentra in tutti i rapporti giuridici di un\'altra, a causa di morte (successione mortis causa) o per atto tra vivi (successione inter vivos).' },
  { termine: 'Tutela giurisdizionale', categoria: 'Diritto costituzionale', definizione: 'Garanzia costituzionale (art. 24 Cost.) che assicura a tutti la possibilità di agire in giudizio per la tutela dei propri diritti e interessi legittimi.' },
  { termine: 'Accesso agli atti', categoria: 'Diritto amministrativo', definizione: 'Diritto degli interessati di prendere visione ed estrarre copia dei documenti amministrativi nei casi previsti dalla legge.' },
{ termine: 'Accesso civico', categoria: 'Diritto amministrativo', definizione: 'Diritto di chiunque di richiedere documenti, dati o informazioni che la pubblica amministrazione abbia omesso di pubblicare.' },
{ termine: 'Accesso civico generalizzato', categoria: 'Diritto amministrativo', definizione: 'Diritto di accedere ai dati e documenti detenuti dalla pubblica amministrazione, anche oltre gli obblighi di pubblicazione, salvo i limiti previsti dalla legge.' },
{ termine: 'Accertamento', categoria: 'Diritto tributario', definizione: 'Attività con cui l’amministrazione finanziaria verifica l’esistenza e l’entità dell’obbligazione tributaria.' },
{ termine: 'Accollo', categoria: 'Diritto civile', definizione: 'Contratto con cui un terzo assume il debito del debitore verso il creditore.' },
{ termine: 'Acquiescenza', categoria: 'Diritto processuale', definizione: 'Comportamento della parte che accetta una sentenza rinunciando all’impugnazione.' },
{ termine: 'Azione revocatoria', categoria: 'Diritto civile', definizione: 'Azione diretta a far dichiarare inefficaci gli atti compiuti dal debitore in pregiudizio del creditore.' },
{ termine: 'Azione surrogatoria', categoria: 'Diritto civile', definizione: 'Potere del creditore di esercitare i diritti del debitore che quest’ultimo trascura di far valere.' },
{ termine: 'Alienazione', categoria: 'Diritto civile', definizione: 'Trasferimento della proprietà o di altro diritto da un soggetto a un altro.' },
{ termine: 'Anatocismo', categoria: 'Diritto bancario', definizione: 'Produzione di interessi sugli interessi già maturati.' },
{ termine: 'Annullamento d’ufficio', categoria: 'Diritto amministrativo', definizione: 'Provvedimento con cui la pubblica amministrazione elimina un proprio atto illegittimo.' },
{ termine: 'Anticorruzione', categoria: 'Diritto amministrativo', definizione: 'Insieme delle misure dirette a prevenire fenomeni corruttivi nella pubblica amministrazione.' },
{ termine: 'Appello', categoria: 'Diritto processuale', definizione: 'Mezzo di impugnazione ordinario con cui si chiede il riesame della sentenza da parte del giudice di grado superiore.' },
{ termine: 'Arbitrato', categoria: 'Diritto processuale', definizione: 'Metodo alternativo di risoluzione delle controversie affidato a uno o più arbitri.' },
{ termine: 'Assegno bancario', categoria: 'Diritto commerciale', definizione: 'Titolo di credito contenente l’ordine rivolto a una banca di pagare una determinata somma.' },
{ termine: 'Assegno circolare', categoria: 'Diritto bancario', definizione: 'Titolo di credito emesso da una banca che promette il pagamento di una somma determinata.' },
{ termine: 'Atto amministrativo', categoria: 'Diritto amministrativo', definizione: 'Manifestazione di volontà della pubblica amministrazione produttiva di effetti giuridici.' },
{ termine: 'Atto nullo', categoria: 'Diritto civile', definizione: 'Atto privo di effetti giuridici per mancanza di requisiti essenziali o per contrarietà alla legge.' },
{ termine: 'Autonomia privata', categoria: 'Diritto civile', definizione: 'Potere dei privati di disciplinare liberamente i propri interessi mediante negozi giuridici.' },
{ termine: 'Avvalimento', categoria: 'Diritto amministrativo', definizione: 'Istituto che consente a un operatore economico di utilizzare i requisiti di un altro soggetto negli appalti pubblici.' },
{ termine: 'Avviso di garanzia', categoria: 'Diritto processuale', definizione: 'Atto con cui l’indagato viene informato del compimento di attività difensive garantite.' },
{ termine: 'Azienda', categoria: 'Diritto commerciale', definizione: 'Complesso dei beni organizzati dall’imprenditore per l’esercizio dell’impresa.' },
{ termine: 'Bilancio', categoria: 'Diritto commerciale', definizione: 'Documento contabile che rappresenta la situazione economica, patrimoniale e finanziaria di un ente o di una società.' },
{ termine: 'Buona fede', categoria: 'Diritto civile', definizione: 'Principio che impone correttezza e lealtà nei rapporti giuridici.' },
{ termine: 'Capacità di agire', categoria: 'Diritto civile', definizione: 'Idoneità del soggetto a compiere validamente atti giuridici.' },
{ termine: 'Capacità giuridica', categoria: 'Diritto civile', definizione: 'Attitudine del soggetto a essere titolare di diritti e obblighi.' },
{ termine: 'Capacità processuale', categoria: 'Diritto processuale', definizione: 'Idoneità del soggetto a stare validamente in giudizio.' },
{ termine: 'Cartella esattoriale', categoria: 'Diritto tributario', definizione: 'Atto con cui l’agente della riscossione richiede il pagamento delle somme dovute.' },
{ termine: 'Caso fortuito', categoria: 'Diritto civile', definizione: 'Evento imprevedibile e inevitabile che esclude la responsabilità.' },
{ termine: 'Cassazione con rinvio', categoria: 'Diritto processuale', definizione: 'Decisione della Corte di Cassazione che annulla la sentenza e rinvia il giudizio ad altro giudice.' },
{ termine: 'Cassazione senza rinvio', categoria: 'Diritto processuale', definizione: 'Decisione della Corte di Cassazione che definisce il giudizio senza rinvio ad altro giudice.' },
{ termine: 'Cessione del credito', categoria: 'Diritto civile', definizione: 'Contratto con cui il creditore trasferisce il proprio credito a un altro soggetto.' },
{ termine: 'Cessione del contratto', categoria: 'Diritto civile', definizione: 'Accordo con cui una parte trasferisce a un terzo la propria posizione contrattuale.' },
{ termine: 'Clausola vessatoria', categoria: 'Diritto civile', definizione: 'Clausola che determina un significativo squilibrio a danno del consumatore.' },
{ termine: 'Compravendita', categoria: 'Diritto civile', definizione: 'Contratto con cui una parte trasferisce la proprietà di un bene verso il pagamento di un prezzo.' },
{ termine: 'Comunione legale', categoria: 'Diritto di famiglia', definizione: 'Regime patrimoniale ordinario della famiglia in cui i beni acquistati durante il matrimonio appartengono a entrambi i coniugi.' },
{ termine: 'Conciliazione', categoria: 'Diritto processuale', definizione: 'Accordo diretto a porre fine a una controversia tra le parti.' },
{ termine: 'Concorrenza sleale', categoria: 'Diritto commerciale', definizione: 'Comportamento contrario alla correttezza professionale posto in essere da un imprenditore.' },
{ termine: 'Conferenza di servizi', categoria: 'Diritto amministrativo', definizione: 'Strumento di coordinamento tra più amministrazioni pubbliche nell’ambito di un procedimento amministrativo.' },
{ termine: 'Confessione', categoria: 'Diritto processuale', definizione: 'Dichiarazione con cui una parte riconosce fatti a sé sfavorevoli.' },
{ termine: 'Conflitto di interessi', categoria: 'Diritto amministrativo', definizione: 'Situazione in cui un interesse privato interferisce con l’esercizio imparziale di una funzione pubblica.' },
{ termine: 'Consenso informato', categoria: 'Diritto civile', definizione: 'Manifestazione libera e consapevole del paziente rispetto a un trattamento sanitario.' },
{ termine: 'Consiglio di Stato', categoria: 'Diritto amministrativo', definizione: 'Organo di consulenza giuridico-amministrativa e giudice di appello della giustizia amministrativa.' },
{ termine: 'Contabilità pubblica', categoria: 'Diritto amministrativo', definizione: 'Insieme delle norme che disciplinano la gestione delle entrate e delle spese pubbliche.' },
{ termine: 'Contratto collettivo nazionale (CCNL)', categoria: 'Diritto del lavoro', definizione: 'Accordo stipulato tra organizzazioni sindacali dei lavoratori e dei datori di lavoro per disciplinare i rapporti di lavoro di un settore.' },
{ termine: 'Contratto consensuale', categoria: 'Diritto civile', definizione: 'Contratto che si perfeziona con il semplice consenso delle parti.' },
{ termine: 'Contratto reale', categoria: 'Diritto civile', definizione: 'Contratto che si perfeziona con la consegna della cosa.' },
{ termine: 'Controllo di legittimità', categoria: 'Diritto amministrativo', definizione: 'Verifica della conformità di un atto alle norme giuridiche.' },
{ termine: 'Corruzione', categoria: 'Diritto penale', definizione: 'Reato consistente nell’accordo illecito tra pubblico ufficiale e privato.' },
{ termine: 'Costituzione rigida', categoria: 'Diritto costituzionale', definizione: 'Costituzione modificabile solo mediante procedimento aggravato rispetto alla legge ordinaria.' },
{ termine: 'Credito privilegiato', categoria: 'Diritto civile', definizione: 'Credito assistito da una causa legittima di prelazione.' },
{ termine: 'Custodia', categoria: 'Diritto civile', definizione: 'Potere materiale su una cosa con obbligo di vigilanza e conservazione.' },
{ termine: 'Danno biologico', categoria: 'Diritto civile', definizione: 'Lesione dell’integrità psicofisica della persona medicalmente accertabile.' },
{ termine: 'Danno emergente', categoria: 'Diritto civile', definizione: 'Perdita economica immediata subita dal soggetto danneggiato.' },
{ termine: 'Danno morale', categoria: 'Diritto civile', definizione: 'Sofferenza interiore derivante da un fatto illecito.' },
{ termine: 'Danno patrimoniale', categoria: 'Diritto civile', definizione: 'Pregiudizio economicamente valutabile subito dal danneggiato.' },
{ termine: 'Decadenza', categoria: 'Diritto civile', definizione: 'Perdita di un diritto per mancato esercizio entro il termine previsto dalla legge.' },
{ termine: 'Decreto ingiuntivo', categoria: 'Diritto processuale', definizione: 'Provvedimento del giudice che ordina al debitore di pagare una somma o consegnare una cosa.' },
{ termine: 'Deliberazione', categoria: 'Diritto amministrativo', definizione: 'Decisione adottata da un organo collegiale.' },
{ termine: 'Demanio', categoria: 'Diritto amministrativo', definizione: 'Complesso dei beni appartenenti allo Stato destinati all’uso pubblico.' },
{ termine: 'Deposizione', categoria: 'Diritto processuale', definizione: 'Dichiarazione resa da un testimone davanti al giudice.' },
{ termine: 'Determinazione dirigenziale', categoria: 'Diritto amministrativo', definizione: 'Atto adottato dal dirigente pubblico nell’esercizio delle proprie competenze.' },
{ termine: 'Difetto di motivazione', categoria: 'Diritto amministrativo', definizione: 'Vizio dell’atto amministrativo consistente nell’assenza o insufficienza delle ragioni della decisione.' },
{ termine: 'Difetto di giurisdizione', categoria: 'Diritto processuale', definizione: 'Mancanza del potere del giudice di decidere una controversia.' },
{ termine: 'Diritto potestativo', categoria: 'Diritto civile', definizione: 'Potere attribuito a un soggetto di modificare unilateralmente la sfera giuridica altrui.' },
{ termine: 'Disapplicazione', categoria: 'Diritto europeo', definizione: 'Mancata applicazione della norma interna incompatibile con il diritto dell’Unione Europea.' },
{ termine: 'Discrezionalità amministrativa', categoria: 'Diritto amministrativo', definizione: 'Margine di scelta riconosciuto alla pubblica amministrazione nella cura dell’interesse pubblico.' },
{ termine: 'Disdetta', categoria: 'Diritto civile', definizione: 'Comunicazione con cui una parte manifesta la volontà di non rinnovare un contratto.' },
{ termine: 'Domicilio', categoria: 'Diritto civile', definizione: 'Luogo in cui una persona ha stabilito la sede principale dei propri affari e interessi.' },
{ termine: 'Eccesso di potere', categoria: 'Diritto amministrativo', definizione: 'Vizio dell’atto amministrativo che ricorre quando il potere viene esercitato in modo illogico o per finalità diverse da quelle previste dalla legge.' },
{ termine: 'Efficacia retroattiva', categoria: 'Teoria del diritto', definizione: 'Capacità di una norma di produrre effetti anche per fatti verificatisi prima della sua entrata in vigore.' },
{ termine: 'Esecutività', categoria: 'Diritto processuale', definizione: 'Attitudine di un provvedimento a essere immediatamente eseguito.' },
{ termine: 'Elusione fiscale', categoria: 'Diritto tributario', definizione: 'Comportamento volto ad aggirare il sistema fiscale sfruttando lacune normative senza violare formalmente la legge.' },
{ termine: 'Esimente', categoria: 'Diritto penale', definizione: 'Circostanza che esclude la punibilità del soggetto.' },
{ termine: 'Evasione fiscale', categoria: 'Diritto tributario', definizione: 'Comportamento illecito diretto a sottrarre redditi o imponibili alla tassazione.' },
{ termine: 'Fallimento', categoria: 'Diritto commerciale', definizione: 'Procedura concorsuale applicata all’imprenditore insolvente.' },
{ termine: 'Falso ideologico', categoria: 'Diritto penale', definizione: 'Alterazione della verità nel contenuto di un atto pubblico.' },
{ termine: 'Falso materiale', categoria: 'Diritto penale', definizione: 'Alterazione materiale di un documento autentico o formazione di documento falso.' },
{ termine: 'Filiazione', categoria: 'Diritto di famiglia', definizione: 'Rapporto giuridico che lega genitori e figli.' },
{ termine: 'Forza maggiore', categoria: 'Diritto civile', definizione: 'Evento straordinario e inevitabile che impedisce l’adempimento.' },
{ termine: 'Franchigia', categoria: 'Diritto assicurativo', definizione: 'Parte del danno che resta a carico dell’assicurato.' },
{ termine: 'Frode fiscale', categoria: 'Diritto tributario', definizione: 'Condotta fraudolenta diretta a sottrarre imponibile al fisco.' },
{ termine: 'Funzione pubblica', categoria: 'Diritto amministrativo', definizione: 'Attività esercitata nell’interesse della collettività da soggetti pubblici.' },
{ termine: 'Garanzia reale', categoria: 'Diritto civile', definizione: 'Garanzia che attribuisce al creditore un diritto su un bene del debitore.' },
{ termine: 'Giudice naturale', categoria: 'Diritto costituzionale', definizione: 'Giudice precostituito per legge competente a decidere una controversia.' },
{ termine: 'Giudizio di ottemperanza', categoria: 'Diritto amministrativo', definizione: 'Procedimento volto a ottenere l’esecuzione delle sentenze amministrative.' },
{ termine: 'Immunità parlamentare', categoria: 'Diritto costituzionale', definizione: 'Garanzia riconosciuta ai membri del Parlamento per assicurare l’indipendenza della funzione parlamentare.' },
{ termine: 'Impresa', categoria: 'Diritto commerciale', definizione: 'Attività economica organizzata diretta alla produzione o allo scambio di beni o servizi.' },
{ termine: 'Improcedibilità', categoria: 'Diritto processuale', definizione: 'Situazione che impedisce la prosecuzione del processo.' },
{ termine: 'Incompatibilità', categoria: 'Diritto costituzionale', definizione: 'Situazione in cui una funzione non può essere esercitata insieme a un’altra carica o attività.' },
{ termine: 'Indennizzo', categoria: 'Diritto civile', definizione: 'Somma dovuta per compensare un sacrificio imposto legittimamente.' },
{ termine: 'Inefficacia', categoria: 'Diritto civile', definizione: 'Inidoneità di un atto a produrre effetti giuridici.' },
{ termine: 'Infrazione europea', categoria: 'Diritto europeo', definizione: 'Violazione del diritto dell’Unione Europea da parte di uno Stato membro.' },
{ termine: 'Insider trading', categoria: 'Diritto commerciale', definizione: 'Utilizzo illecito di informazioni privilegiate nelle operazioni finanziarie.' },
{ termine: 'Interdizione', categoria: 'Diritto civile', definizione: 'Provvedimento che priva il soggetto incapace della capacità di agire.' },
{ termine: 'Interesse legittimo', categoria: 'Diritto amministrativo', definizione: 'Posizione giuridica soggettiva tutelata nei confronti dell’esercizio del potere amministrativo.' },
{ termine: 'Interesse pubblico', categoria: 'Diritto amministrativo', definizione: 'Finalità collettiva perseguita dall’azione della pubblica amministrazione.' },
{ termine: 'Interpretazione autentica', categoria: 'Fonti del diritto', definizione: 'Interpretazione fornita direttamente dal legislatore con efficacia vincolante.' },
{ termine: 'Interruzione della prescrizione', categoria: 'Diritto civile', definizione: 'Evento che azzera il decorso del termine prescrizionale.' },
{ termine: 'Irretroattività', categoria: 'Teoria del diritto', definizione: 'Principio secondo cui la legge dispone solo per il futuro.' },
{ termine: 'IVA (Imposta sul Valore Aggiunto)', categoria: 'Diritto tributario', definizione: 'Imposta indiretta sui consumi applicata sul valore aggiunto generato nelle diverse fasi produttive e commerciali.' },
{ termine: 'Legittimazione ad agire', categoria: 'Diritto processuale', definizione: 'Titolarità del potere di promuovere o contraddire un giudizio.' },
{ termine: 'Legittimo affidamento', categoria: 'Diritto amministrativo', definizione: 'Tutela della fiducia del cittadino nella stabilità e correttezza dell’azione amministrativa.' },
{ termine: 'Licenziamento', categoria: 'Diritto del lavoro', definizione: 'Atto unilaterale con cui il datore di lavoro scioglie il rapporto di lavoro subordinato.' },
{ termine: 'Liquidazione', categoria: 'Diritto commerciale', definizione: 'Procedimento volto alla definizione dei rapporti patrimoniali di una società cessata.' },
{ termine: 'Litisconsorzio', categoria: 'Diritto processuale', definizione: 'Partecipazione di più soggetti nel medesimo processo.' },
{ termine: 'Lucro cessante', categoria: 'Diritto civile', definizione: 'Mancato guadagno derivante dal fatto dannoso.' },
{ termine: 'Mansioni', categoria: 'Diritto del lavoro', definizione: 'Insieme delle attività che il lavoratore è tenuto a svolgere in base al contratto di lavoro.' },
{ termine: 'Mediazione', categoria: 'Diritto processuale', definizione: 'Procedura alternativa di composizione delle controversie con l’assistenza di un mediatore.' },
{ termine: 'Memoria difensiva', categoria: 'Diritto processuale', definizione: 'Atto scritto con cui la parte espone difese e argomentazioni.' },
{ termine: 'Mobbing', categoria: 'Diritto del lavoro', definizione: 'Comportamento vessatorio sistematico che lede la dignità e la salute del lavoratore.' },
{ termine: 'Motivi aggiunti', categoria: 'Diritto amministrativo', definizione: 'Ulteriori censure introdotte nel giudizio amministrativo dopo il ricorso iniziale.' },
{ termine: 'Negozio giuridico', categoria: 'Diritto civile', definizione: 'Manifestazione di volontà diretta a produrre effetti giuridici riconosciuti dall’ordinamento.' },
{ termine: 'Nulla poena sine lege', categoria: 'Diritto penale', definizione: 'Principio secondo cui nessuna pena può essere applicata senza una legge che la preveda.' },
{ termine: 'Obbligazione tributaria', categoria: 'Diritto tributario', definizione: 'Vincolo giuridico che impone al contribuente il pagamento del tributo.' },
{ termine: 'Onere della prova', categoria: 'Diritto processuale', definizione: 'Obbligo della parte di dimostrare i fatti posti a fondamento della domanda o dell’eccezione.' },
{ termine: 'Opposizione', categoria: 'Diritto processuale', definizione: 'Mezzo con cui si contesta un provvedimento giudiziario.' },
{ termine: 'Ordine pubblico', categoria: 'Teoria del diritto', definizione: 'Insieme dei principi fondamentali inderogabili dell’ordinamento giuridico.' },
{ termine: 'Patrimonio', categoria: 'Diritto civile', definizione: 'Complesso dei rapporti giuridici attivi e passivi facenti capo a un soggetto.' },
{ termine: 'Pignoramento', categoria: 'Diritto processuale', definizione: 'Atto con cui ha inizio l’espropriazione forzata dei beni del debitore.' },
{ termine: 'Potere discrezionale', categoria: 'Diritto amministrativo', definizione: 'Facoltà della pubblica amministrazione di scegliere tra più soluzioni lecite.' },
{ termine: 'Potere vincolato', categoria: 'Diritto amministrativo', definizione: 'Potere amministrativo esercitabile secondo modalità rigidamente fissate dalla legge.' },
{ termine: 'Precetto', categoria: 'Diritto processuale', definizione: 'Atto con cui il creditore intima al debitore di adempiere l’obbligo risultante dal titolo esecutivo.' },
{ termine: 'Prelazione', categoria: 'Diritto civile', definizione: 'Diritto di essere preferito ad altri nell’acquisto di un bene alle stesse condizioni.' },
{ termine: 'Presunzione', categoria: 'Diritto processuale', definizione: 'Conseguenza che la legge o il giudice trae da un fatto noto per risalire a un fatto ignoto.' },
{ termine: 'Primato del diritto UE', categoria: 'Diritto europeo', definizione: 'Principio per cui il diritto dell’Unione Europea prevale sul diritto interno degli Stati membri.' },
{ termine: 'Privacy', categoria: 'Diritto civile', definizione: 'Diritto alla riservatezza e alla protezione dei dati personali.' },
{ termine: 'Procedimento amministrativo', categoria: 'Diritto amministrativo', definizione: 'Sequenza di atti finalizzati all’adozione del provvedimento amministrativo.' },
{ termine: 'Procura', categoria: 'Diritto civile', definizione: 'Atto con cui un soggetto attribuisce a un altro il potere di rappresentarlo.' },
{ termine: 'Procura speciale', categoria: 'Diritto processuale', definizione: 'Mandato conferito per il compimento di specifici atti processuali.' },
{ termine: 'Prova documentale', categoria: 'Diritto processuale', definizione: 'Mezzo di prova costituito da documenti scritti.' },
{ termine: 'Provvedimento amministrativo', categoria: 'Diritto amministrativo', definizione: 'Atto unilaterale con cui la pubblica amministrazione esercita il proprio potere.' },
{ termine: 'Pubblico ufficiale', categoria: 'Diritto penale', definizione: 'Soggetto che esercita una pubblica funzione legislativa, giudiziaria o amministrativa.' },
{ termine: 'Quorum costituzionale', categoria: 'Diritto costituzionale', definizione: 'Maggioranza qualificata richiesta dalla Costituzione per l’approvazione di determinati atti.' },
{ termine: 'Ratifica', categoria: 'Diritto internazionale', definizione: 'Atto con cui lo Stato conferma definitivamente un trattato internazionale.' },
{ termine: 'Reato continuato', categoria: 'Diritto penale', definizione: 'Pluralità di reati commessi in esecuzione di un medesimo disegno criminoso.' },
{ termine: 'Reato tentato', categoria: 'Diritto penale', definizione: 'Ipotesi in cui il soggetto compie atti idonei diretti a commettere un reato senza riuscire a consumarlo.' },
{ termine: 'Recesso', categoria: 'Diritto civile', definizione: 'Facoltà di sciogliersi unilateralmente da un contratto nei casi previsti dalla legge o dal contratto.' },
{ termine: 'Referendum abrogativo', categoria: 'Diritto costituzionale', definizione: 'Consultazione popolare diretta all’abrogazione totale o parziale di una legge.' },
{ termine: 'Referendum costituzionale', categoria: 'Diritto costituzionale', definizione: 'Consultazione popolare prevista per confermare o respingere una legge di revisione costituzionale.' },
{ termine: 'Regolamento amministrativo', categoria: 'Diritto amministrativo', definizione: 'Fonte normativa secondaria emanata dalla pubblica amministrazione.' },
{ termine: 'Responsabilità amministrativa', categoria: 'Diritto amministrativo', definizione: 'Responsabilità del dipendente pubblico per danni arrecati all’erario.' },
{ termine: 'Responsabilità disciplinare', categoria: 'Diritto del lavoro', definizione: 'Responsabilità derivante dalla violazione dei doveri lavorativi.' },
{ termine: 'Responsabilità oggettiva', categoria: 'Diritto civile', definizione: 'Responsabilità che prescinde dall’accertamento della colpa.' },
{ termine: 'Revoca', categoria: 'Diritto amministrativo', definizione: 'Provvedimento con cui la pubblica amministrazione elimina un proprio atto per sopravvenuti motivi di interesse pubblico.' },
{ termine: 'Revocazione', categoria: 'Diritto processuale', definizione: 'Mezzo straordinario di impugnazione contro sentenze affette da particolari vizi.' },
{ termine: 'Ricorso al TAR', categoria: 'Diritto amministrativo', definizione: 'Impugnazione proposta davanti al Tribunale Amministrativo Regionale contro un atto amministrativo illegittimo.' },
{ termine: 'Rinvio pregiudiziale', categoria: 'Diritto europeo', definizione: 'Procedura con cui il giudice nazionale sottopone una questione interpretativa alla Corte di Giustizia UE.' },
{ termine: 'Risoluzione del contratto', categoria: 'Diritto civile', definizione: 'Scioglimento del contratto per inadempimento, impossibilità sopravvenuta o eccessiva onerosità.' },
{ termine: 'Riserva di legge', categoria: 'Diritto costituzionale', definizione: 'Principio per cui determinate materie possono essere disciplinate solo dalla legge.' },
{ termine: 'Rito ordinario', categoria: 'Diritto processuale', definizione: 'Procedimento civile caratterizzato dalla piena cognizione del giudice.' },
{ termine: 'Sciopero', categoria: 'Diritto del lavoro', definizione: 'Astensione collettiva dal lavoro per la tutela di interessi economici e professionali.' },
];